### ISSUE TITLE
data_state.py

### ISSUE THREAD

**Issue by kadir-gunel** [tuzhaopeng/NMT#4]
Hello @tuzhaopeng ,

In data_state.py file you named a variable dim which is equal to 1000. Is this the dimension of the word vectors or the hidden layer size? 

And also could you please tell me what are the meaning/usages of these variables ; could not manage to find their meaning : 

null_sym_source=16000,
null_sym_target=16000,
n_sym_source=16001,
n_sym_target=16001,
use_linguistic_coverage=False,

B.R.
Kadir

**Comment by kadir-gunel** [comment]
I noticed that there is no dev set for updating weights. Did I miss something?

**Comment by tuzhaopeng** [comment]
> In data_state.py file you named a variable dim which is equal to 1000. Is this the dimension of the word vectors or the hidden layer size?

It is hidden layer size. The dimensionality of word vector is 620.

> And also could you please tell me what are the meaning/usages of these variables ; could not manage to find their meaning :

# These are end-of-sequence marks
    state['null_sym_source'] = None
    state['null_sym_target'] = None
    # These are vocabulary sizes for the source and target languages
    state['n_sym_source'] = None
    state['n_sym_target'] = None

use_linguistic_coverage is an indicator on whether or not to use linguistic coverage, details of which can be found in my ACL paper (http://arxiv.org/abs/1601.04811) .

More descriptions of the options can be found in the file state.py

> I noticed that there is no dev set for updating weights.

The dev set is used to decide when to stop the training, rather than updating weights. You need to save the model for every K iterations and run test.sh to get translation performance on your own dev set.
